apiVersion: v1
kind: Service
metadata:
  name: httpecho-both
  labels:
    state.internal.workloads.kcp.dev/kcp-cluster-1: ""
    state.internal.workloads.kcp.dev/kcp-cluster-2: ""
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    app: echo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  labels:
    state.internal.workloads.kcp.dev/kcp-cluster-1: ""
    state.internal.workloads.kcp.dev/kcp-cluster-2: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: jmalloc/echo-server
          ports:
            - name: http-port
              containerPort: 8080
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nondomain
  labels:
    state.internal.workloads.kcp.dev/kcp-cluster-1: ""
    state.internal.workloads.kcp.dev/kcp-cluster-2: ""
spec:
  rules:
    - host: host.whatever.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpecho-both
                port:
                  number: 80
