apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        - name: external-dns
          args:
            - --provider=aws
            - --aws-zone-type=public
            - --source=crd
            - --log-level=debug
            - --annotation-filter=type=global
            - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
            - --crd-source-kind=DNSEndpoint
            - --policy=sync
            - --registry=txt
            - --txt-prefix=kcp-glbc-

#external-dns options pkg/apis/externaldns/types.go
