apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  annotations: {}
  name: glbc
spec:
  permissionClaims:
    - group: ""
      resource: secrets
      state: Accepted
    - group: ""
      identityHash: IDENTITY_HASH
      resource: services
      state: Accepted
    - group: apps
      identityHash: IDENTITY_HASH
      resource: deployments
      state: Accepted
    - group: networking.k8s.io
      identityHash: IDENTITY_HASH
      resource: ingresses
      state: Accepted
  reference:
    workspace:
      exportName: glbc
      path: root:kuadrant
