name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.17
      - uses: golangci/golangci-lint-action@v2
        with:
          only-new-issues: true
          args: --timeout=5m

  codegen:
    name: codegen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.17
      - name: Check generate
        run: make verify-generate

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.17
      - run: make build
      - run: PATH="${PATH}:$(pwd)/bin/" make test
